### PR TITLE
Feature/support images

### PR DESCRIPTION
**Pull request by ludov04**
copy the figures folder to local so it gets sync to s3, which we can then redirect from rdocumentation.org

### CODE REVIEW

**Comment by filipsch** [comment]
@ludov04 I transfered ownership of pkgdown to datacamp. Can you update the Dockerfile and the `DESCRIPTION` file accordingly?

**Comment by ludov04** [comment]
done!

**Review by filipsch — APPROVED** [review]
LGTM

**Comment by filipsch** [comment]
You'll have to create a new release on GitHub when you merge this in. If you're fast enough, the Jenkins job can already find the new release when building the image ;)

**Pull request merged**
